### ISSUE TITLE
"master" still used in .platform.app.yml after changing branch to main

### ISSUE THREAD

**Issue by bertsmets** [platformsh-templates/strapi#31]
Hi,

after changing the default master branch to main (to comply with GitHub) by following the Platform.sh guide, this template still tests for a branch named "master" to determine the environment to start with.

I noticed that my application was deployed with the development environment after changing the branch from master to main, resulting in a 502 Bad Gateway

Locally I have simply adjusted the file, would have been nice if this was accounted for or mentioned in the guide

**Comment by bertsmets** [comment]
https://github.com/platformsh-templates/strapi/blob/master/.platform.app.yaml#L78

**Comment by fredpotvin-platformsh** [comment]
@bertsmets is correct. There is an issue with this template at L78.

First, Platform.sh has changed it's default production branch name from `master` to `main` so new projects will fail with this.

Second, the production environment can have any name. So, relying on a string will fail when the name is changed and the service will fail to start.
