### ISSUE TITLE
Write access for api folder

### ISSUE THREAD

**Issue by aruno14** [platformsh-templates/strapi#54]
Hello,

I had to add the below code to `.platform.app.yaml` to be able to create new collections:
```
mounts:
  "api":
    source: local
    source_path: api
```

**Comment by chadwcarlson** [comment]
Hi @aruno14 ! Thanks for the issue. We had this exact addition included in the template originally, however we were advised by the Strapi team to run this template in production when deployed. Adding new collections, or anything else that requires a development Strapi server to be run needs to be done locally.
